CREATE ROLE [db_SSBDeveloper]
AUTHORIZATION [dbo]
GO
EXEC sp_addrolemember N'db_SSBDeveloper', N'SSBCLOUD\BI Developers'
GO
GRANT CREATE PROCEDURE TO [db_SSBDeveloper]
GRANT CREATE TABLE TO [db_SSBDeveloper]
GRANT CREATE VIEW TO [db_SSBDeveloper]
GRANT DELETE TO [db_SSBDeveloper]
GRANT EXECUTE TO [db_SSBDeveloper]
GRANT INSERT TO [db_SSBDeveloper]
GRANT SELECT TO [db_SSBDeveloper]
GRANT SHOWPLAN TO [db_SSBDeveloper]
GRANT VIEW DEFINITION TO [db_SSBDeveloper]
