CREATE TABLE [audit].[Marekto_All_People]
(
[Account Owner Email Address] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account Owner First Name] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account Owner Last Name] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Acquisition Date] [datetime] NULL,
[Acquisition Program] [varchar] (33) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address] [varchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Annual Revenue] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Anonymous IP] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Billing Address] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Billing City] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Billing Country] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Billing Postal Code] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Billing State] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Black Listed] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Black Listed Cause] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Card Ship Date] [datetime] NULL,
[City] [varchar] (41) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Club Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Coaching Expiration] [datetime] NULL,
[Coaching Level] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CoachingCert Expiration] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment Capture] [datetime] NULL,
[Comment History] [datetime] NULL,
[Company Name] [varchar] (34) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Company Notes] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Country] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Created At] [datetime] NULL,
[Date of Birth] [datetime] NULL,
[Department] [datetime] NULL,
[Do Not Call] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Do Not Call Cause] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Do Not Call Reason] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Duathlon Event Name] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email Address] [varchar] (42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email Invalid] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email Invalid Cause] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email Suspended] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email Suspended At] [datetime] NULL,
[Email Suspended Cause] [varchar] (316) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fax Number] [varchar] (294) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First Name] [varchar] (230) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Full Name] [varchar] (42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Industry] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Inferred City] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Inferred Company] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Inferred Country] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Inferred Metropolitan Area] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Inferred Phone Area Code] [varchar] (43) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Inferred Postal Code] [varchar] (29) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Inferred State Region] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Is Customer] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Is Partner] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Job Title] [varchar] (48) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Interesting Moment Date] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Interesting Moment Desc] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Interesting Moment Source] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Interesting Moment Type] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Name] [varchar] (29) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Notes] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales Owner Email Address] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales Owner First Name] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales Owner Job Title] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales Owner Last Name] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales Owner Phone Number] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Person Rating] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Person Role] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Person Score] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Person Source] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Person Status] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Level] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MZ Feedback 2017] [varchar] (377) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Main Phone] [varchar] (109) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketing Suspended] [varchar] (138) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketing Suspended Cause] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketing Suspended Reason] [bigint] NULL,
[Marketo Jigsaw Company ID] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Jigsaw Company Status] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Jigsaw Contact ID] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Jigsaw Contact Status] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Facebook Display Name] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Facebook Id] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Facebook Photo URL] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Facebook Profile URL] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Facebook Reach] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Facebook Referred Enrollments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Facebook Referred Visits] [datetime] NULL,
[Marketo Social Gender] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Last Referred Enrollment] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Last Referred Visit] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social LinkedIn Display Name] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social LinkedIn Id] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social LinkedIn Photo URL] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social LinkedIn Profile URL] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social LinkedIn Reach] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social LinkedIn Referred Enrollments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social LinkedIn Referred Visits] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Syndication ID] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Total Referred Enrollments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Total Referred Visits] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Twitter Display Name] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Twitter Id] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Twitter Photo URL] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Twitter Profile URL] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Twitter Reach] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Twitter Referred Enrollments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Twitter Referred Visits] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Unique Code] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Unique Name] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Media Outlet] [varchar] (43) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Member Id] [varchar] (43) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Member Number] [int] NULL,
[Membership Expiration Date] [datetime] NULL,
[Middle Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mobile Phone Number] [smallint] NULL,
[Number Of Employees] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Number of Opportunities ] [smallint] NULL,
[Original Referrer] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Original Search Engine] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Original Search Phrase] [varchar] (65) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Original Source Info] [varchar] (89) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Original Source Type] [varchar] (79) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PI Code] [varchar] (48) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Parent Company Name] [varchar] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Person Notes] [varchar] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Person Time Zone] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone Number] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Postal Code] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Priority] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Registration Source Info] [varchar] (89) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Registration Source Type] [varchar] (79) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Relative Score] [varchar] (48) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Relative Urgency] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SIC Code] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Salutation] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Segmentation_Gender_1005] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Segmentation_Region_1001] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Site] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sprint Podium Place] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sprint Race Name] [varchar] (39) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subscription - Educational] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subscription - Electronic Magazine] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subscription - Events] [smallint] NULL,
[Subscription - Last Updated] [smallint] NULL,
[Subscription - Newsletter] [smallint] NULL,
[Subscription - Print Magazine] [smallint] NULL,
[Subscription - Product Updates] [smallint] NULL,
[Subscription - Tri It Forward] [smallint] NULL,
[Subscription - Webinars] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subscription-exclusive discounts and offers] [smallint] NULL,
[Subscription-news for members] [smallint] NULL,
[Total Opportunity Amount] [smallint] NULL,
[Total Opportunity Expected Revenue] [smallint] NULL,
[Unsubscribed] [smallint] NULL,
[Unsubscribed Cause] [varchar] (57) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unsubscribed Reason] [varchar] (57) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Updated At] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Urgency] [datetime] NULL,
[Website] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[autorenewdate] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bike] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[onedaysurveyURL] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[run] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[swim] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trainingPlanUrl] [varchar] (58) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[utm_source] [varchar] (46) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
