CREATE TABLE [ods].[Marketo_Leads]
(
[ETL_ID] [int] NOT NULL IDENTITY(1, 1),
[ETL_CreatedDate] [datetime] NOT NULL CONSTRAINT [DF__USAT_Mark__ETL_C__522FEADD] DEFAULT (getdate()),
[ETL_UpdatedDate] [datetime] NOT NULL CONSTRAINT [DF__USAT_Mark__ETL_U__53240F16] DEFAULT (getdate()),
[ETL_isdeleted] [bit] NOT NULL CONSTRAINT [DF__USAT_Mark__ETL_i__5418334F] DEFAULT ((0)),
[ETL_DeletedDate] [datetime] NULL,
[ETL_DeltaHashkey] [binary] (32) NULL,
[ETL_FileName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[acquisitionProgramId] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[autorenewdate] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bike] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cardShipDate] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[clubName] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[coachingExpiration] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[coachingLevel] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[commentCapture] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[country] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdAt] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dateOfBirth] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[duathlonEventName] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Id] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inferredStateRegion] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[level] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mainPhone] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[marketingSuspendedReason] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mediaOutlet] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[memberId] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[memberNumber] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[membershipExpirationDate] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[middleName] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mktoAcquisitionDate] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mobilePhone] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mZFeedback2017] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[originalReferrer] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[originalSearchEngine] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[phone] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[postalCode] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rating] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[registrationSourceInfo] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[registrationSourceType] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[relativeScore] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[run] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[salutation] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sprintPodiumPlace] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sprintRaceName] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[subscriptionEducational] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[subscriptionEvents] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[subscriptionLastUpdated] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[subscriptionNewsletter] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[subscriptionProductUpdates] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[subscriptionWebinars] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[swim] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[title] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trainingPlanUrl] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UpdatedAt] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [ods].[Marketo_Leads] ADD CONSTRAINT [PK__USAT_Mar__7EF6BFCD56961C7C] PRIMARY KEY CLUSTERED  ([ETL_ID])
GO
