CREATE TABLE [stg].[Marketo_All_People]
(
[Account Owner Email Address] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account Owner First Name] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account Owner Last Name] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Acquisition Date] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Acquisition Program] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Annual Revenue] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Anonymous IP] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Billing Address] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Billing City] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Billing Country] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Billing Postal Code] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Billing State] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Black Listed] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Black Listed Cause] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Card Ship Date] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Club Name] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Coaching Expiration] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Coaching Level] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CoachingCert Expiration] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment Capture] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment History] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Company Name] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Company Notes] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Country] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Created At] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date of Birth] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Department] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Do Not Call] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Do Not Call Cause] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Do Not Call Reason] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Duathlon Event Name] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email Address] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email Invalid] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email Invalid Cause] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email Suspended] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email Suspended At] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email Suspended Cause] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column 40] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fax Number] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column 42] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First Name] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Full Name] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Industry] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Inferred City] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Inferred Company] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Inferred Country] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Inferred Metropolitan Area] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Inferred Phone Area Code] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Inferred Postal Code] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Inferred State Region] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Is Customer] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Is Partner] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Job Title] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Interesting Moment Date] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Interesting Moment Desc] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Interesting Moment Source] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Interesting Moment Type] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Name] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Notes] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales Owner Email Address] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales Owner First Name] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales Owner Job Title] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales Owner Last Name] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales Owner Phone Number] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Person Rating] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Person Role] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Person Score] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Person Source] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Person Status] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Level] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MZ Feedback 2017] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column 74] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Main Phone] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column 76] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketing Suspended] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketing Suspended Cause] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketing Suspended Reason] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Jigsaw Company ID] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Jigsaw Company Status] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Jigsaw Contact ID] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Jigsaw Contact Status] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Facebook Display Name] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Facebook Id] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Facebook Photo URL] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Facebook Profile URL] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Facebook Reach] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Facebook Referred Enrollments] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Facebook Referred Visits] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Gender] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Last Referred Enrollment] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Last Referred Visit] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social LinkedIn Display Name] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social LinkedIn Id] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social LinkedIn Photo URL] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social LinkedIn Profile URL] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social LinkedIn Reach] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social LinkedIn Referred Enrollments] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social LinkedIn Referred Visits] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Syndication ID] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Total Referred Enrollments] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Total Referred Visits] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Twitter Display Name] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Twitter Id] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Twitter Photo URL] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Twitter Profile URL] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Twitter Reach] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Twitter Referred Enrollments] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Social Twitter Referred Visits] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Unique Code] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marketo Unique Name] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Media Outlet] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Member Id] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Member Number] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Membership Expiration Date] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Middle Name] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mobile Phone Number] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Number Of Employees] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Number of Opportunities ] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Original Referrer] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Original Search Engine] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Original Search Phrase] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Original Source Info] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Original Source Type] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PI Code] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Parent Company Name] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Person Time Zone] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone Number] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Postal Code] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Priority] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Registration Source Info] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Registration Source Type] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Relative Score] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Relative Urgency] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SIC Code] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Salutation] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Segmentation_Gender_1005] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Segmentation_Region_1001] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Site] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sprint Podium Place] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sprint Race Name] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subscription - Educational] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subscription - Electronic Magazine] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subscription - Events] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subscription - Last Updated] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subscription - Newsletter] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subscription - Print Magazine] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subscription - Product Updates] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subscription - Tri It Forward] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subscription - Webinars] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subscription-exclusive discounts and offers] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subscription-news for members] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Total Opportunity Amount] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Total Opportunity Expected Revenue] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unsubscribed] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unsubscribed Cause] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unsubscribed Reason] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Updated At] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Urgency] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Website] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[autorenewdate] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bike] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[onedaysurveyURL] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[run] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[swim] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trainingPlanUrl] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[utm_source] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
