CREATE SCHEMA [apietl]
AUTHORIZATION [dbo]
GO
GRANT ALTER ON SCHEMA:: [apietl] TO [db_apiETL]
GO
GRANT DELETE ON SCHEMA:: [apietl] TO [db_apiETL]
GO
GRANT EXECUTE ON SCHEMA:: [apietl] TO [db_apiETL]
GO
GRANT INSERT ON SCHEMA:: [apietl] TO [db_apiETL]
GO
GRANT SELECT ON SCHEMA:: [apietl] TO [db_apiETL]
GO
GRANT UPDATE ON SCHEMA:: [apietl] TO [db_apiETL]
GO
GRANT ALTER ON SCHEMA:: [apietl] TO [db_SSBDeveloper]
GO
