CREATE SCHEMA [ods]
AUTHORIZATION [dbo]
GO
GRANT ALTER ON SCHEMA:: [ods] TO [db_apiETL]
GO
GRANT DELETE ON SCHEMA:: [ods] TO [db_apiETL]
GO
GRANT INSERT ON SCHEMA:: [ods] TO [db_apiETL]
GO
GRANT SELECT ON SCHEMA:: [ods] TO [db_apiETL]
GO
GRANT UPDATE ON SCHEMA:: [ods] TO [db_apiETL]
GO
GRANT ALTER ON SCHEMA:: [ods] TO [db_SSBDeveloper]
GO
GRANT UPDATE ON SCHEMA:: [ods] TO [db_SSBDeveloper]
GO
